-- Canonical schema entrypoint for HRToolkit India.
-- Preferred deployment path:
--   1) supabase db push
-- This applies every migration under supabase/migrations/ in order.
-- If using the SQL editor manually, run:
--   1) supabase/migrations/001_initial.sql
--   2) supabase/migrations/002_phase1_hardening.sql
