"use client";
import {useEffect,useState} from "react";
export default function Admin(){
 const [pw,setPw]=useState(""),[logged,setLogged]=useState(false),[orders,setOrders]=useState<any[]>([]),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/admin/orders");if(r.ok){setLogged(true);setOrders(await r.json())}}
 useEffect(()=>{load()},[]);
 async function login(){setMsg("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})});const d=await r.json();if(!r.ok){setMsg(d.error||"Login failed");return}setLogged(true);load()}
 async function action(id:string,action:string){setMsg("");const r=await fetch("/api/admin/payment-action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:id,action})});const d=await r.json();if(!r.ok){setMsg(d.error||"Action failed");return}setMsg(id+" → "+d.status);load()}
 async function generate(id:string){setMsg("");const r=await fetch("/api/admin/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:id})});const d=await r.json();setMsg(r.ok?id+" → DELIVERED":d.error||"Delivery failed");load()}
 return <main style={{fontFamily:"system-ui",background:"#f6f8fc",minHeight:"100vh",padding:"32px"}}><div style={{maxWidth:1200,margin:"auto"}}><h1>HRToolKit India — Admin</h1>{!logged?<div style={{background:"#fff",padding:24,borderRadius:16,maxWidth:420}}><p>Secure admin access</p><input style={{width:"100%",padding:12}} type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Admin password"/><button style={{marginTop:12,padding:12,width:"100%"}} onClick={login}>Sign in</button>{msg&&<p>{msg}</p>}</div>:<><p>{msg}</p><button onClick={load}>Refresh</button><div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",background:"#fff",borderCollapse:"collapse"}}><thead><tr><th>Order</th><th>Customer</th><th>Template</th><th>Platform</th><th>Amount</th><th>UTR</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.name}<br/>{o.delivery_email}</td><td>{o.template_slug}</td><td>{o.platform}</td><td>₹{o.amount}</td><td>{o.utr||"—"}</td><td>{o.status}</td><td style={{whiteSpace:"nowrap"}}>{o.status==="PAYMENT_SUBMITTED"&&<><button onClick={()=>action(o.id,"DELIVER")}>Payment Received</button> <button onClick={()=>action(o.id,"NOT_RECEIVED")}>Not Received</button></>}{o.status==="GENERATING"&&<button onClick={()=>generate(o.id)}>Generate & Deliver</button>}{o.status==="REVISION_REQUESTED"&&<button onClick={()=>generate(o.id)}>Regenerate & Deliver</button>}</td></tr>)}</tbody></table></div></>}</div></main>
}