create extension if not exists pgcrypto;

create table if not exists templates (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null check (price > 0),
  platforms text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id text primary key,
  customer_access_token_hash text unique not null,
  name text not null,
  contact_number text not null,
  email text not null,
  delivery_email text not null,
  template_slug text not null references templates(slug),
  platform text not null check (platform in ('excel','powerbi','googlesheets','powerautomate','tableau')),
  requirements text not null check (char_length(requirements) between 30 and 10000),
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'INR' check (currency = 'INR'),
  status text not null check (status in ('PENDING_PAYMENT','PAYMENT_SUBMITTED','PAYMENT_NOT_RECEIVED','GENERATING','AWAITING_ADMIN_CONFIRMATION','REVISION_REQUESTED','DELIVERED','FAILED')),
  utr text unique,
  payment_screenshot_url text,
  sample_file_url text,
  idempotency_key_hash text unique,
  created_ip inet,
  payment_submitted_at timestamptz,
  generation_started_at timestamptz,
  generation_completed_at timestamptz,
  delivered_at timestamptz,
  generation_error text,
  ai_attempts integer not null default 0 check (ai_attempts between 0 and 3),
  ai_cost_usd numeric(12,6) not null default 0 check (ai_cost_usd >= 0),
  revision_count integer not null default 0 check (revision_count between 0 and 2),
  admin_action text,
  admin_action_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists consents (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  terms_version text not null,
  required_consent boolean not null,
  offers_consent boolean not null default false,
  revision_consent boolean not null,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now(),
  withdrawn_at timestamptz
);

create table if not exists revisions (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  message text not null check (char_length(message) between 10 and 5000),
  revision_number integer not null check (revision_number between 1 and 2),
  created_at timestamptz not null default now()
);

create table if not exists deliverables (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  file_url text,
  file_name text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  created_at timestamptz not null default now()
);

create table if not exists email_logs (
  id bigint generated by default as identity primary key,
  order_id text references orders(id) on delete set null,
  recipient text not null,
  template text not null,
  status text not null check (status in ('SENT','FAILED')),
  provider_message_id text,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists admin_actions (
  id bigint generated by default as identity primary key,
  order_id text references orders(id) on delete set null,
  action text not null,
  actor text not null default 'admin',
  source text not null check (source in ('SESSION','SIGNED_EMAIL_LINK','SYSTEM')),
  ip inet,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists ai_runs (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  run_type text not null check (run_type in ('BUILDER','QA_REVIEWER')),
  attempt integer not null check (attempt between 1 and 3),
  model text not null,
  status text not null check (status in ('STARTED','SUCCEEDED','FAILED')),
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(12,6) not null default 0 check (cost_usd >= 0),
  error text,
  created_at timestamptz not null default now()
);

create unique index if not exists revisions_order_number on revisions(order_id, revision_number);
create index if not exists orders_status_created_idx on orders(status, created_at desc);
create index if not exists orders_email_idx on orders(lower(email));
create index if not exists orders_created_ip_idx on orders(created_ip);
create index if not exists ai_runs_order_idx on ai_runs(order_id, created_at desc);
create index if not exists email_logs_order_idx on email_logs(order_id, created_at desc);
create index if not exists admin_actions_order_idx on admin_actions(order_id, created_at desc);

alter table templates enable row level security;
alter table orders enable row level security;
alter table consents enable row level security;
alter table revisions enable row level security;
alter table deliverables enable row level security;
alter table email_logs enable row level security;
alter table admin_actions enable row level security;
alter table ai_runs enable row level security;

-- No public/anon policies are intentionally created.
-- Server-side requests use the Supabase service-role key.
-- Never expose the service-role key to browser code.

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists templates_set_updated_at on templates;
create trigger templates_set_updated_at
before update on templates
for each row execute function set_updated_at();

drop trigger if exists orders_set_updated_at on orders;
create trigger orders_set_updated_at
before update on orders
for each row execute function set_updated_at();
