-- Phase 1 hardening migration.
-- Adds lifecycle, retention and single-use admin action foundations without changing
-- the approved manual-UPI / human-payment-confirmation model.

alter table orders
  add column if not exists sample_file_expires_at timestamptz,
  add column if not exists payment_screenshot_expires_at timestamptz,
  add column if not exists generation_deadline_at timestamptz,
  add column if not exists generation_alerted_at timestamptz;

create unique index if not exists orders_utr_case_insensitive_unique
  on orders (upper(utr))
  where utr is not null;

create table if not exists action_tokens (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  action text not null check (action in ('DELIVER','NOT_RECEIVED')),
  token_hash text unique not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists action_tokens_order_action_idx
  on action_tokens(order_id, action, expires_at);

alter table action_tokens enable row level security;

create unique index if not exists ai_runs_one_active_builder_per_order
  on ai_runs(order_id)
  where run_type = 'BUILDER' and status = 'STARTED';

alter table consents
  drop constraint if exists consents_required_true;

alter table consents
  add constraint consents_required_true check (required_consent = true);

alter table consents
  drop constraint if exists consents_revision_true;

alter table consents
  add constraint consents_revision_true check (revision_consent = true);

alter table orders
  drop constraint if exists orders_admin_action_check;

alter table orders
  add constraint orders_admin_action_check
  check (admin_action is null or admin_action in ('DELIVER','NOT_RECEIVED'));

-- Retention is intentionally represented on each file-bearing order so the cleanup
-- worker can delete only after delivery + 30 days without touching tax/accounting data.
